# Generated by Django 5.2.7 on 2025-11-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0001_initial'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'Vacuna Registrada', 'verbose_name_plural': 'Vacunas Registradas'},
        ),
        migrations.AddField(
            model_name='vaccine',
            name='baby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='babies.baby', verbose_name='Bebé asociado'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='applied_at',
            field=models.DateField(verbose_name='Fecha de aplicación'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la vacuna'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('AP', 'Aplicada'), ('PE', 'Pendiente')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
