# Generated by Django 5.2.7 on 2025-11-03 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_alter_vaccine_options_vaccine_baby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
