# Generated by Django 5.2.7 on 2025-11-08 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido en formato Markdown', verbose_name='Contenido del aviso')),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash SHA-256')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Aviso de privacidad',
                'verbose_name_plural': 'Avisos de privacidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Aceptado el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('privacy_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='privacy.privacynotice', verbose_name='Aviso de privacidad')),
            ],
            options={
                'verbose_name': 'Aceptación de aviso de privacidad',
                'verbose_name_plural': 'Aceptaciones de avisos de privacidad',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'privacy_notice')},
            },
        ),
    ]
