# Generated by Django 5.2.7 on 2025-11-08 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.BooleanField(default=True, help_text='Finalidades necesarias para el funcionamiento del servicio (requeridas)', verbose_name='Operativas')),
                ('analitica', models.BooleanField(default=False, help_text='Análisis de uso y estadísticas', verbose_name='Analíticas')),
                ('marketing', models.BooleanField(default=False, help_text='Envío de notificaciones promocionales y comunicaciones comerciales', verbose_name='Marketing')),
                ('personalizacion', models.BooleanField(default=False, help_text='Personalización de contenido y experiencia', verbose_name='Personalización')),
                ('investigacion', models.BooleanField(default=False, help_text='Uso de datos para investigación y desarrollo (anonimizados)', verbose_name='Investigación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
            },
        ),
    ]
