# Generated by Django 5.2.7 on 2025-10-27 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileparent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profileparent',
            name='prifle_key',
        ),
        migrations.RemoveField(
            model_name='profileparent',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='profilespecialist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profilespecialist',
            name='prifle_key',
        ),
        migrations.RemoveField(
            model_name='profilespecialist',
            name='profile_id',
        ),
        migrations.AlterField(
            model_name='profileparent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(app_label)s_%(class)s_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilespecialist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(app_label)s_%(class)s_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
