# Generated by Django 5.2.7 on 2025-11-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_profileparent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del bebé')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso del bebé en kilogramos', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('alergias', models.TextField(blank=True, help_text='Registra alergias conocidas del bebé', verbose_name='Alergias')),
                ('condiciones_salud', models.TextField(blank=True, help_text='Condiciones médicas, enfermedades crónicas, etc.', verbose_name='Condiciones de salud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='accounts.profileparent', verbose_name='Padre/Madre')),
            ],
            options={
                'verbose_name': 'Bebé',
                'verbose_name_plural': 'Bebés',
                'ordering': ['-fecha_nacimiento'],
            },
        ),
    ]
