# Generated by Django 5.2.7 on 2025-11-08 01:38

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='alergias',
            field=core.fields.EncryptedTextField(blank=True, help_text='Registra alergias conocidas del bebé (cifrado)', verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='baby',
            name='condiciones_salud',
            field=core.fields.EncryptedTextField(blank=True, help_text='Condiciones médicas, enfermedades crónicas, etc. (cifrado)', verbose_name='Condiciones de salud'),
        ),
    ]
