# Generated by Django 5.2.7 on 2025-11-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_profileparent_email_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje de la notificación')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('notification_type', models.CharField(choices=[('comment', 'Nuevo Comentario'), ('vaccine_3_days', 'Recordatorio Vacuna (3 días)'), ('vaccine_today', 'Recordatorio Vacuna (Hoy)')], max_length=20, verbose_name='Tipo de Notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profileparent', verbose_name='Usuario (Padre/Madre)')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
